### ISSUE TITLE
ResponseError('operation not permitted',)

### ISSUE THREAD

**Issue by nisang** [JoneXiong/PyRedisAdmin#11]
ops! Error 500: Internal Server Error

Sorry, the requested URL http://10.0.0.239:8585/overview caused an error:

Unhandled exception
Exception:

ResponseError('operation not permitted',)
Traceback:

Traceback (most recent call last):
  File "/usr/src/myapp/pyredisadmin/mole/mole.py", line 243, in handle
    return handler(**args)
  File "/usr/src/myapp/pyredisadmin/mole/mole.py", line 181, in wrapper
    response.output = func(*a, **ka)
  File "./routes.py", line 75, in overview
    return template('overview', redis_info=get_redis_info(), media_prefix=media_prefix)
  File "/usr/src/myapp/pyredisadmin/over_view.py", line 52, in get_redis_info
    info_dict =client.info()
  File "/usr/src/myapp/pyredisadmin/redis/client.py", line 657, in info
    return self.execute_command('INFO')
  File "/usr/src/myapp/pyredisadmin/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/src/myapp/pyredisadmin/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/usr/src/myapp/pyredisadmin/redis/connection.py", line 574, in read_response
    raise response
ResponseError: operation not permitted

**Comment by nisang** [comment]
### python version:python 2.7.9

**Comment by JoneXiong** [comment]
你的redis服务设置了需要密码访问，在config.py里'password'配置项那填上密码再启动就可以了
